// ============================================================
// catalog-data.js
// ------------------------------------------------------------
// RAW DATA ONLY. No logic lives in this file on purpose.
// This is every real filename from utsav.zip, grouped by the
// 14 folders under /assets, plus the business config for each
// category (display label, rental-vs-service type, card size
// tier, price range, blurb). catalog.js (the next file) reads
// this object and turns it into actual priced, rated items.
//
// Loaded as a plain <script> (not fetch/JSON) on purpose: opening
// index.html straight from disk (file://) blocks fetch() of local
// JSON in most browsers. A script tag has no such restriction, so
// the whole site still works with zero server and zero build step.
// ============================================================

const CATALOG_DATA = {
  "BRIDAL_WEAR": {
    "label": "Bridal Wear",
    "slug": "bridal-wear",
    "type": "rental",
    "boxTier": "sm",
    "blurb": "Lehengas, gowns, sarees and sangeet sets — the full bridal wardrobe, available to rent.",
    "priceRange": [
      1800,
      3900
    ],
    "unit": "/ day",
    "files": [
      "bb1.jpg",
      "bb2.jpg",
      "bb3.jpg",
      "bb4.jpg",
      "bb5.jpg",
      "bb6.jpg",
      "bb7.jpg",
      "bb8.jpg",
      "bb9.jpg",
      "bb10.jpg",
      "bb11.jpg",
      "bb12.jpg",
      "bb13.jpg",
      "bb14.jpg",
      "bb15.jpg",
      "bb16.jpg",
      "bb17.jpg",
      "bb18.jpg",
      "bb19.jpg",
      "bb20.jpg",
      "bb21.jpg",
      "bb22.jpg",
      "bb23.jpg",
      "bb24.jpg",
      "bb25.jpg",
      "bb26.jpg",
      "bb27.jpg",
      "bb28.jpg",
      "bb29.jpg",
      "bb30.jpg",
      "bb31.jpg",
      "bb32.jpg",
      "bb33.jpg",
      "bb34.jpg",
      "bb35.jpg",
      "bb36.jpg",
      "bb37.jpg",
      "bb38.jpg",
      "bb39.jpg",
      "bb40.jpg",
      "bb41.jpg",
      "bb42.jpg",
      "bb43.jpg",
      "bb44.jpg",
      "bb45.jpg",
      "bb46.jpg",
      "bb47.jpg",
      "bb48.jpg",
      "bb49.jpg",
      "bb50.jpg",
      "bb51.jpg",
      "bb52.jpg",
      "bb53.jpg",
      "bb54.jpg",
      "bb55.jpg",
      "bb56.jpg",
      "bb57.jpg",
      "bb58.jpg",
      "bb59.jpg",
      "bb60.jpg",
      "bb61.jpg",
      "bb62.jpg",
      "bb63.jpg",
      "bb64.jpg",
      "bb65.jpg",
      "bb66.jpg",
      "bb67.jpg",
      "bb68.jpg",
      "bb69.jpg",
      "bb70.jpg",
      "bb71.jpg",
      "bb72.jpg",
      "bb73.jpg",
      "bb74.jpg",
      "bb75.jpg",
      "bb76.jpg",
      "bb77.jpg",
      "bb78.jpg",
      "bb79.jpg",
      "bb80.jpg",
      "bb81.jpg",
      "bb82.jpg",
      "bb83.jpg",
      "bb84.jpg",
      "bb85.jpg",
      "bb86.png",
      "bb87.jpg",
      "bb88.png",
      "bb89.jpg",
      "bb90.jpg",
      "bb91.jpg",
      "bb92.jpg",
      "bb93.jpg",
      "bb94.jpg",
      "bb95.jpg",
      "bb96.jpg",
      "bb97.jpg",
      "bb98.jpg",
      "bb99.jpg",
      "bb100.jpg",
      "bb101.jpg",
      "bb102.jpg",
      "bb103.jpg",
      "bb104.jpg",
      "bb105.jpg",
      "bb106.jpg",
      "bb107.jpg",
      "bb108.jpg",
      "bb109.jpg",
      "bb110.png",
      "bb111.jpg",
      "bb112.jpg",
      "bb113.jpg",
      "bb114.jpg",
      "bb115.jpg",
      "bb116.jpg",
      "bb117.jpg",
      "bb118.jpg",
      "bb119.jpg",
      "bb120.jpg",
      "bb121.jpg",
      "bb122.jpg",
      "bb123.jpg",
      "bb124.jpg",
      "bb125.jpg",
      "bb126.jpg",
      "bb127.jpg",
      "bb128.jpg",
      "bb129.jpg",
      "bb130.jpg",
      "bb131.jpg",
      "bb132.jpg",
      "bb133.jpg",
      "bb134.jpg",
      "bb135.jpg"
    ],
    "count": 135
  },
  "GROOM_WEAR": {
    "label": "Groom Wear",
    "slug": "groom-wear",
    "type": "rental",
    "boxTier": "sm",
    "blurb": "Sherwanis, jodhpuris and bandhgalas tailored for the wedding party.",
    "priceRange": [
      1500,
      3500
    ],
    "unit": "/ day",
    "files": [
      "g1.jpg",
      "g2.png",
      "g3.jpg",
      "g4.jpg",
      "g5.jpg",
      "g6.png",
      "g7.jpg",
      "g8.jpg",
      "g9.jpg",
      "g10.jpg",
      "g11.jpg",
      "g12.jpg",
      "g13.jpg",
      "g14.jpg",
      "g15.jpg",
      "g16.jpg",
      "g17.jpg",
      "g18.jpg",
      "g19.jpg",
      "g20.jpg",
      "g21.jpg",
      "g22.jpg",
      "g23.jpg",
      "g24.jpg",
      "g25.jpg",
      "g26.jpg",
      "g27.jpg",
      "g28.jpg",
      "g29.jpg",
      "g30.png",
      "g31.jpg",
      "g32.jpg",
      "g33.jpg",
      "g34.jpg",
      "g35.jpg",
      "g36.jpg",
      "g37.jpg",
      "g38.jpg",
      "g39.jpg",
      "h40.jpg",
      "g41.jpg",
      "g42.jpg",
      "g43.jpg",
      "g44.jpg",
      "g45.jpg",
      "g46.jpg",
      "g47.jpg",
      "g48.jpg",
      "g49.jpg",
      "g50.jpg",
      "g51.jpg",
      "g52.jpg",
      "g53.jpg",
      "g54.jpg",
      "g55.jpg",
      "g56.jpg",
      "g57.jpg",
      "g58.jpg",
      "g59.jpg",
      "g60.jpg",
      "g61.jpg",
      "g62.jpg",
      "g63.jpg",
      "g64.jpg",
      "g65.jpg",
      "g66.jpg",
      "g67.jpg",
      "g68.jpg",
      "g69.jpg",
      "g70.jpg",
      "g71.jpg",
      "g72.jpg",
      "g73.png",
      "g74.jpg",
      "g75.jpg",
      "g76.jpg",
      "g77.jpg",
      "g78.jpg",
      "g79.jpg",
      "g80.jpg",
      "g81.jpg",
      "g82.jpg",
      "g83.jpg",
      "g84.jpg",
      "g85.jpg",
      "g86.jpg",
      "g87.jpg",
      "g88.png",
      "g89.jpg",
      "g90.png",
      "g91.jpg",
      "g92.jpg",
      "g93.jpg",
      "g94.jpg",
      "g95.jpg",
      "g96.jpg",
      "g97.jpg",
      "g98.jpg",
      "g99.jpg",
      "g100.jpg",
      "g101.jpg",
      "g102.jpg",
      "g103.jpg",
      "g104.jpg",
      "g105.jpg",
      "g106.jpg",
      "g107.jpg",
      "g108.jpg",
      "g109.jpg",
      "g110.jpg",
      "g111.jpg",
      "g112.jpg",
      "g113.jpg",
      "g114.jpg",
      "g115.jpg",
      "g116.jpg",
      "g117.jpg",
      "g118.jpg",
      "g119.jpg",
      "g120.jpg",
      "g121.jpg"
    ],
    "count": 121
  },
  "COUPLE_SETS": {
    "label": "Couple Sets",
    "slug": "couple-sets",
    "type": "rental",
    "boxTier": "sm",
    "blurb": "Matching his-and-hers outfits, built for coordinated photographs.",
    "priceRange": [
      2000,
      3950
    ],
    "unit": "/ day",
    "files": [
      "cp1.jpg",
      "cp2.jpg",
      "cp3.jpg",
      "cp4.jpg",
      "cp5.jpg",
      "cp6.jpg",
      "cp7.jpg",
      "cp8.jpg",
      "cp9.jpg",
      "cp10.jpg",
      "cp11.jpg",
      "cp12.jpg",
      "cp13.jpg",
      "cp14.jpg",
      "cp15.jpg",
      "cp16.jpg",
      "cp17.jpg",
      "cp18.jpg",
      "cp19.jpg",
      "cp20.jpg",
      "cp21.jpg",
      "cp22.jpg",
      "cp23.jpg",
      "cp24.jpg",
      "cp25.jpg",
      "cp26.jpg",
      "cp27.jpg",
      "cp28.jpg",
      "cp29.jpg",
      "cp30.jpg",
      "cp31.jpg",
      "cp32.jpg",
      "cp33.jpg",
      "cp34.jpg",
      "cp35.jpg",
      "cp36.jpg",
      "cp37.jpg",
      "cp38.jpg",
      "cp39.jpg",
      "cp40.jpg",
      "cp41.jpg",
      "cp42.jpg",
      "cp43.jpg",
      "cp44.jpg",
      "cp45.jpg",
      "cp46.jpg",
      "cp47.jpg",
      "cp48.jpg",
      "cp49.jpg",
      "cp50.jpg",
      "cp51.jpg",
      "cp52.jpg",
      "cp53.jpg",
      "cp54.jpg",
      "cp55.png",
      "cp56.jpg",
      "cp57.jpg",
      "cp58.jpg",
      "cp59.jpg",
      "cp60.jpg",
      "cp61.jpg",
      "cp62.jpg",
      "cp63.jpg",
      "cp64.jpg"
    ],
    "count": 64
  },
  "BRIDAL_JEWELLERY": {
    "label": "Bridal Jewellery",
    "slug": "bridal-jewellery",
    "type": "rental",
    "boxTier": "min",
    "blurb": "Kundan, polki and temple-finish sets, rented with insured handling.",
    "priceRange": [
      900,
      2600
    ],
    "unit": "/ day",
    "files": [
      "j1.jpg",
      "j2.jpg",
      "j3.jpg",
      "j4.jpg",
      "j5.jpg",
      "j6.jpg",
      "j7.jpg",
      "j8.jpg",
      "j9.png",
      "j10.jpg",
      "j11.jpg",
      "j12.jpg",
      "j13.jpg",
      "j14.jpg",
      "j15.jpg",
      "j16.jpg",
      "j17.jpg",
      "j18.jpg",
      "j19.jpg",
      "j20.jpg",
      "j21.jpg",
      "j22.jpg",
      "j23.png",
      "j24.jpg",
      "j25.jpg",
      "j26.jpg",
      "j27.jpg",
      "j28.jpg",
      "j29.jpg",
      "j30.jpg",
      "j31.jpeg",
      "j32.jpeg",
      "j33.jpeg",
      "j34.jpeg",
      "j35.jpeg",
      "j36.jpeg",
      "j37.jpeg",
      "j38.jpeg",
      "j39.jpeg",
      "j40.jpeg",
      "j41.jpeg",
      "j42.jpeg",
      "j43.jpeg",
      "j44.jpeg",
      "j45.jpeg",
      "j46.jpeg",
      "j47.jpeg",
      "j48.jpeg",
      "j49.jpeg",
      "j50.jpeg",
      "j51.jpeg",
      "j52.jpeg",
      "j53.jpeg",
      "j54.jpeg",
      "j55.jpeg",
      "j56.jpeg",
      "j57.jpeg",
      "j58.jpeg",
      "j59.jpeg",
      "j60.jpeg",
      "j61.jpeg",
      "j62.jpeg",
      "j63.jpeg",
      "j64.jpg",
      "j65.jpg",
      "j66.jpg",
      "j67.jpg",
      "j68.jpg",
      "j70.jpg",
      "j71.jpg",
      "j72.jpg",
      "j73.jpg",
      "j74.jpg",
      "j75.jpg",
      "j76.jpg",
      "j77.jpg",
      "j78.jpg",
      "j80.jpg",
      "j81.jpg",
      "j82.jpg",
      "j83.jpg",
      "j84.jpg",
      "j85.jpg",
      "j86.jpg",
      "j87.jpg",
      "j88.jpg",
      "j89.jpg",
      "j90.jpg",
      "j91.jpg",
      "j92.jpg",
      "j93.jpg",
      "j94.jpg",
      "j95.jpg",
      "j96.jpg",
      "j97.jpg",
      "j98.jpg",
      "j99.jpg",
      "j100.jpg",
      "j101.jpg"
    ],
    "count": 99
  },
  "GROOM_JEWELLERY": {
    "label": "Groom Jewellery",
    "slug": "groom-jewellery",
    "type": "rental",
    "boxTier": "min",
    "blurb": "Kalgis, malas and brooch sets to finish a groom's look.",
    "priceRange": [
      700,
      2000
    ],
    "unit": "/ day",
    "files": [
      "JG1.jpg",
      "JG2.jpg",
      "JG3.jpg",
      "JG4.jpg",
      "JG5.jpg",
      "JG6.jpg",
      "JG7.jpg",
      "JG8.jpg",
      "JG9.jpg",
      "JG10.jpg",
      "JG11.jpg",
      "JG12.jpg",
      "JG13.jpg",
      "JG14.jpg",
      "JG15.jpg",
      "JG16.jpg",
      "JG17.jpg",
      "JG18.jpg",
      "JG19.jpg",
      "JG20.jpg",
      "JG21.jpg",
      "JG22.jpg",
      "JG23.jpg",
      "JG24.jpg",
      "JG25.jpg",
      "JG26.jpg",
      "JG27.jpg",
      "JG28.jpg",
      "JG29.jpg",
      "JG30.jpg",
      "JG31.jpg",
      "JG32.jpg",
      "JG33.jpg",
      "JG34.jpg",
      "JG35.jpg",
      "JG36.jpg",
      "JG37.jpg",
      "JG38.jpg",
      "JG39.jpg",
      "JG40.jpg",
      "JG41.jpg",
      "JG42.jpg",
      "JG43.jpg",
      "JG44.jpg",
      "JG45.jpg",
      "JG46.jpg",
      "JG47.jpg",
      "JG48.jpg",
      "JG49.jpg",
      "JG50.jpg",
      "JG51.jpg",
      "JG52.jpg",
      "JG53.jpg",
      "JG54.jpg",
      "JG55.jpg",
      "JG56.jpg",
      "JG57.jpg",
      "JG58.jpg",
      "JG59.jpg",
      "JG60.jpg",
      "JG61.jpg",
      "JG62.jpg",
      "JG63.jpg",
      "JG64.jpg",
      "JG65.jpg",
      "JG66.jpg",
      "JG67.jpg",
      "JG68.jpg",
      "JG69.jpg",
      "JG70.jpg",
      "JG71.jpg",
      "JG72.jpg",
      "JG73.jpg",
      "JG74.jpg",
      "JG75.jpg",
      "JG76.jpg",
      "JG77.jpg",
      "JG78.jpg",
      "JG79.jpg",
      "JG80.jpg",
      "JG81.jpg",
      "JG82.jpg",
      "JG83.jpg",
      "JG84.jpg",
      "JG85.jpg",
      "JG86.jpg",
      "JG87.jpg",
      "JG88.jpg",
      "JG89.jpg",
      "JG90.jpg",
      "JG91.jpg",
      "JG92.jpg",
      "JG93.jpg",
      "JG94.jpg",
      "JG95.jpg",
      "JG96.jpg",
      "JG97.jpg",
      "JG98.jpg",
      "JG99.jpg",
      "JG100.jpg",
      "JG101.jpg",
      "JG102.jpg",
      "JG103.jpg",
      "JG104.jpg",
      "JG105.jpg",
      "JG106.jpg",
      "JG107.jpg",
      "JG108.jpg",
      "JG109.jpg"
    ],
    "count": 109
  },
  "JUTI_FOOTWEAR": {
    "label": "Juti & Footwear",
    "slug": "juti-footwear",
    "type": "rental",
    "boxTier": "min",
    "blurb": "Hand-embroidered juti and mojari, sized for a full day on your feet.",
    "priceRange": [
      300,
      900
    ],
    "unit": "/ day",
    "files": [
      "J1.jpg",
      "J2.jpg",
      "J3.jpg",
      "J4.jpg",
      "J5.jpg",
      "J6.jpg",
      "J7.jpg",
      "J8.jpg",
      "J9.jpg",
      "J10.jpg",
      "J11.jpg",
      "J12.jpg",
      "J13.jpg",
      "J14.jpg",
      "J15.jpg",
      "J16.jpg",
      "J17.jpg",
      "J18.jpg",
      "J19.jpg",
      "J20.jpg",
      "J21.jpg",
      "J22.jpg",
      "J23.jpg",
      "J24.jpg",
      "J25.jpg",
      "J26.jpg",
      "J27.jpg",
      "J28.jpg",
      "J29.jpg",
      "J30.jpg",
      "J31.jpg",
      "J32.jpg",
      "J33.jpg",
      "J34.jpg",
      "J35.jpg",
      "J36.jpg",
      "J37.jpg",
      "J38.jpg",
      "J39.jpg",
      "J40.jpg",
      "J41.jpg",
      "J42.jpg",
      "J43.jpg",
      "J44.jpg",
      "J45.jpg",
      "J46.jpg",
      "J47.jpg",
      "J48.jpg",
      "J49.jpg",
      "J50.jpg",
      "J51.jpg",
      "J52.jpg",
      "J53.jpg",
      "J54.jpg",
      "J55.jpg",
      "J56.jpg",
      "J57.jpg",
      "J58.jpg"
    ],
    "count": 58
  },
  "PAGDI_SAFA": {
    "label": "Pagdi & Safa",
    "slug": "pagdi-safa",
    "type": "rental",
    "boxTier": "min",
    "blurb": "Hand-tied turbans and safas, styled and pinned on the day.",
    "priceRange": [
      400,
      1300
    ],
    "unit": "/ day",
    "files": [
      "pag1.jpg",
      "pag2.jpg",
      "pag3.jpg",
      "pag4.jpg",
      "pag5.jpg",
      "pag6.jpg",
      "pag7.jpg",
      "pag8.jpg",
      "pag9.jpg",
      "pag10.jpg",
      "pag11.jpg",
      "pag12.jpg",
      "pag13.jpg",
      "pag14.jpg",
      "pag15.jpg",
      "pag16.jpg",
      "pag17.jpg",
      "pag18.jpg",
      "pag19.jpg",
      "pag20.jpg",
      "pag21.jpg",
      "pag22.jpg",
      "pag23.jpg",
      "pag24.jpg",
      "pag25.jpg",
      "pag26.jpg",
      "pag27.jpg",
      "pag28.jpg",
      "pag29.jpg",
      "pag30.jpg",
      "pag31.jpg",
      "pag32.jpg",
      "pag33.jpg",
      "pag34.jpg",
      "pag35.jpg",
      "pag36.jpg",
      "pag37.jpg",
      "pag38.jpg",
      "pag39.jpg",
      "pag40.jpg",
      "pag41.jpg",
      "pag42.jpg",
      "pag43.jpg",
      "pag44.jpg",
      "pag45.jpg",
      "pag46.jpg",
      "pag47.jpg",
      "pag48.jpg",
      "pag49.jpg",
      "pag50.jpg",
      "pag51.jpg",
      "pag52.jpg",
      "pag53.jpg",
      "pag54.jpg",
      "pag55.jpg",
      "pag56.jpg",
      "pag57.jpg",
      "pag58.jpg",
      "pag59.jpg",
      "pag60.jpg",
      "pag61.jpg",
      "pag62.jpg",
      "pag63.jpg",
      "pag64.jpg",
      "pag65.jpg",
      "pag66.jpg",
      "pag67.jpg",
      "pag68.jpg",
      "pag69.jpg",
      "pag70.jpg",
      "pag71.jpg",
      "pag72.jpg",
      "pag73.jpg",
      "pag74.jpg",
      "pag75.jpg",
      "pag76.jpg",
      "pag77.jpg",
      "pag78.jpg",
      "pag79.jpg",
      "pag80.jpg",
      "pag81.jpg",
      "pag82.jpg",
      "pag83.jpg",
      "pag84.jpg",
      "pag85.jpg",
      "pag86.jpg",
      "pag87.jpg",
      "pag88.jpg",
      "pag89.jpg",
      "pag90.jpg",
      "pag91.jpg",
      "pag92.jpg",
      "pag93.jpg",
      "pag94.jpg",
      "pag95.jpg",
      "pag96.jpg",
      "pag97.jpg",
      "pag98.jpg",
      "pag99.jpg",
      "pag100.jpg",
      "pag101.jpg",
      "pag102.jpg",
      "pag103.jpg",
      "pag104.jpg",
      "pag105.jpg"
    ],
    "count": 105
  },
  "HAIR_STYLING": {
    "label": "Hair Styling",
    "slug": "hair-styling",
    "type": "service",
    "boxTier": "max",
    "blurb": "Our single most-booked studio service — keratin, updos, cuts and colour, done by our senior stylists.",
    "priceRange": [
      900,
      4500
    ],
    "unit": "/ session",
    "files": [
      "HS1.jpg",
      "HS2.jpg",
      "HS3.jpg",
      "HS4.jpg",
      "HS5.jpg",
      "HS6.jpg",
      "HS7.jpg",
      "HS8.jpg",
      "HS9.jpg",
      "HS10.jpg",
      "HS11.jpg",
      "HS12.jpg",
      "HS13.jpg",
      "HS14.jpg",
      "HS15.jpg",
      "HS16.jpg",
      "HS17.jpg",
      "HS18.jpg",
      "HS19.jpg",
      "HS20.jpg",
      "HS21.jpg",
      "HS22.jpg",
      "HS23.jpg",
      "HS24.jpg",
      "HS25.jpg",
      "HS26.jpg",
      "HS27.jpg",
      "HS28.jpg",
      "HS29.jpg",
      "HS30.jpg",
      "HS31.jpg",
      "HS32.jpg",
      "HS33.jpg",
      "HS34.jpg",
      "HS35.jpg",
      "HS36.jpg",
      "HS37.jpg",
      "HS38.jpg",
      "HS39.jpg",
      "HS40.jpg",
      "HS41.jpg",
      "HS42.jpg",
      "HS43.jpg",
      "HS44.jpg",
      "HS45.jpg",
      "HS46.jpg",
      "HS47.jpg",
      "HS48.jpg",
      "HS49.jpg",
      "HS50.jpg",
      "HS51.jpg",
      "HS52.jpg",
      "HS53.jpg",
      "HS54.jpg",
      "HS55.jpg",
      "HS56.jpg",
      "HS57.jpg",
      "HS58.png",
      "HS59.png",
      "HS60.jpg",
      "HS61.jpg",
      "HS62.jpg",
      "HS63.jpg",
      "HS64.jpg",
      "HS65.jpg",
      "HS66.jpg",
      "HS67.jpg",
      "HS68.jpg",
      "HS69.jpg",
      "HS70.jpg"
    ],
    "count": 70
  },
  "MAKEUP_LOOKS": {
    "label": "Makeup Looks",
    "slug": "makeup-looks",
    "type": "service",
    "boxTier": "lg",
    "blurb": "Bridal, HD and party makeup, matched to skin tone and camera-ready.",
    "priceRange": [
      1500,
      8000
    ],
    "unit": "/ session",
    "files": [
      "ML1.jpg",
      "ML2.jpg",
      "ML3.jpg",
      "ML4.jpg",
      "ML5.jpg",
      "ML6.jpg",
      "ML7.jpg",
      "ML8.jpg",
      "ML9.jpg",
      "ML10.jpg",
      "ML11.jpg",
      "ML12.jpg",
      "ML13.jpg",
      "ML14.jpg",
      "ML15.jpg",
      "ML16.jpg",
      "ML17.jpg",
      "ML18.jpg",
      "ML19.jpg",
      "ML20.jpg",
      "ML21.jpg",
      "ML22.jpg"
    ],
    "count": 22
  },
  "NAIL_ART": {
    "label": "Nail Art",
    "slug": "nail-art",
    "type": "service",
    "boxTier": "md",
    "blurb": "Hand-painted, chrome, 3D and gel nail art, finished to match the rest of the look.",
    "priceRange": [
      500,
      2200
    ],
    "unit": "/ session",
    "files": [
      "NA1.jpg",
      "NA2.jpg",
      "NA3.jpg",
      "NA4.jpg",
      "NA5.jpg",
      "NA6.jpg",
      "NA7.jpg",
      "NA8.jpg",
      "NA9.jpg",
      "NA10.jpg",
      "NA11.jpg",
      "NA12.jpg",
      "NA13.jpg",
      "NA14.jpg",
      "NA15.jpg",
      "NA16.jpg",
      "NA17.jpg",
      "NA18.jpg",
      "NA19.jpg",
      "NA20.jpg",
      "NA21.jpg",
      "NA22.jpg",
      "NA23.jpg",
      "NA24.jpg",
      "NA25.jpg",
      "NA26.jpg",
      "NA27.jpg",
      "NA28.jpg",
      "NA29.jpg"
    ],
    "count": 29
  },
  "NAIL_CARE": {
    "label": "Nail Care",
    "slug": "nail-care",
    "type": "service",
    "boxTier": "md",
    "blurb": "Manicures and pedicures, the everyday upkeep behind every finished look.",
    "priceRange": [
      400,
      1400
    ],
    "unit": "/ session",
    "files": [
      "NC1.jpg",
      "NC2.jpg",
      "NC3.jpg",
      "NC4.jpg",
      "NC5.jpg",
      "NC6.jpg",
      "NC7.jpg",
      "NC8.jpg",
      "NC9.jpg",
      "NC10.jpg",
      "NC11.jpg",
      "NC12.jpg",
      "NC13.jpg"
    ],
    "count": 13
  },
  "FACE_CARE": {
    "label": "Face Care",
    "slug": "face-care",
    "type": "service",
    "boxTier": "lg",
    "blurb": "Facials matched to skin type, de-tanning and skin-prep treatments.",
    "priceRange": [
      600,
      2800
    ],
    "unit": "/ session",
    "files": [
      "fc1.jpg",
      "fc2.jpg",
      "fc3.jpg",
      "fc4.jpg",
      "fc5.jpg",
      "fc6.png",
      "fc7.jpg"
    ],
    "count": 7
  },
  "FEATURES_WALLPAPERS": {
    "label": "Studio Features",
    "slug": "studio-features",
    "type": "service",
    "boxTier": "sm",
    "blurb": "A look inside the studio itself — our space, our setups, our finished work on display.",
    "priceRange": [
      0,
      0
    ],
    "unit": "",
    "files": [
      "FW1.jpg",
      "FW2.jpg",
      "FW3.jpg",
      "FW4.jpg",
      "FW5.jpg",
      "FW6.jpg",
      "FW7.jpg",
      "FW8.jpg",
      "FW9.jpg",
      "FW10.png",
      "FW11.png",
      "FW12.jpg",
      "FW13.jpg",
      "FW14.jpg",
      "FW15.jpg",
      "FW16.jpg",
      "FW17.jpg",
      "FW18.jpg",
      "FW19.jpg",
      "FW20.jpg",
      "FW21.jpg",
      "FW22.jpg"
    ],
    "count": 22
  },
  "STUDIO_DETAILS": {
    "label": "Studio Details",
    "slug": "studio-details",
    "type": "service",
    "boxTier": "min",
    "blurb": "One more look behind the scenes at Utsav Showroom.",
    "priceRange": [
      0,
      0
    ],
    "unit": "",
    "files": [
      "WhatsApp Image 2026-07-09 at 12.58.46 AM.jpeg"
    ],
    "count": 1
  }
};
