-- ============================================================
-- Brings the database up to date with every schema change made
-- since the original init migration: Admin dual-OTP fields, the
-- new User/OwnerSettings tables, ServiceBooking, AdminOtpChallenge,
-- and the full Customer/Order/BookingDate rental-order system.
--
-- Hand-written (not generated by `prisma migrate dev`, since that
-- requires a live DB connection this environment doesn't have) —
-- verified field-by-field against schema.prisma and the existing
-- init migration's table definitions.
-- ============================================================

-- ---- Admin: dual-OTP + owner-slot fields ----
ALTER TABLE "Admin" ALTER COLUMN "passwordHash" DROP NOT NULL;
ALTER TABLE "Admin" ADD COLUMN "phone" TEXT;
ALTER TABLE "Admin" ADD COLUMN "phoneVerifiedAt" TIMESTAMP(3);
ALTER TABLE "Admin" ADD COLUMN "isRoot" BOOLEAN NOT NULL DEFAULT false;
CREATE UNIQUE INDEX "Admin_phone_key" ON "Admin"("phone");

-- ---- User (real customer accounts) ----
CREATE TABLE "User" (
    "id" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "email" TEXT NOT NULL,
    "passwordHash" TEXT NOT NULL,
    "age" INTEGER,
    "dateOfBirth" TIMESTAMP(3),
    "profileImage" TEXT,
    "role" TEXT NOT NULL DEFAULT 'user',
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "User_pkey" PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX "User_email_key" ON "User"("email");

-- ---- OwnerSettings (singleton row controlling owner slot limit) ----
CREATE TABLE "OwnerSettings" (
    "id" TEXT NOT NULL DEFAULT 'singleton',
    "maxOwnerSlots" INTEGER NOT NULL DEFAULT 1,

    CONSTRAINT "OwnerSettings_pkey" PRIMARY KEY ("id")
);

-- ---- ServiceBooking (Contact page "Book a Slot") ----
CREATE TABLE "ServiceBooking" (
    "id" TEXT NOT NULL,
    "section" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "phone" TEXT NOT NULL,
    "service" TEXT,
    "preferredDate" TIMESTAMP(3),
    "preferredTime" TEXT,
    "note" TEXT,
    "status" TEXT NOT NULL DEFAULT 'new',
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "ServiceBooking_pkey" PRIMARY KEY ("id")
);

-- ---- AdminOtpChallenge (dual-OTP verification state) ----
CREATE TABLE "AdminOtpChallenge" (
    "id" TEXT NOT NULL,
    "email" TEXT NOT NULL,
    "phone" TEXT NOT NULL,
    "emailCodeHash" TEXT NOT NULL,
    "phoneCodeHash" TEXT NOT NULL,
    "emailVerified" BOOLEAN NOT NULL DEFAULT false,
    "phoneVerified" BOOLEAN NOT NULL DEFAULT false,
    "attempts" INTEGER NOT NULL DEFAULT 0,
    "expiresAt" TIMESTAMP(3) NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "AdminOtpChallenge_pkey" PRIMARY KEY ("id")
);

-- ---- Customer (identified by phone, no password — for My Orders) ----
CREATE TABLE "Customer" (
    "id" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "phone" TEXT NOT NULL,
    "email" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "Customer_pkey" PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX "Customer_phone_key" ON "Customer"("phone");

-- ---- Order enums ----
CREATE TYPE "OrderStatus" AS ENUM ('PENDING_PAYMENT', 'CONFIRMED', 'CANCELLED', 'COMPLETED');
CREATE TYPE "PaymentMethod" AS ENUM ('UPI', 'CARD', 'NETBANKING', 'COD');
CREATE TYPE "PaymentStatus" AS ENUM ('PENDING', 'PAID', 'FAILED', 'COD_PENDING');

-- ---- Order (a rental booking + payment) ----
CREATE TABLE "Order" (
    "id" TEXT NOT NULL,
    "customerId" TEXT NOT NULL,
    "postId" TEXT NOT NULL,
    "productName" TEXT NOT NULL,
    "productImage" TEXT,
    "size" TEXT,
    "startDate" TIMESTAMP(3) NOT NULL,
    "endDate" TIMESTAMP(3) NOT NULL,
    "days" INTEGER NOT NULL,
    "purpose" TEXT,
    "pricePerDay" DOUBLE PRECISION NOT NULL,
    "totalAmount" DOUBLE PRECISION NOT NULL,
    "paymentMethod" "PaymentMethod" NOT NULL,
    "paymentStatus" "PaymentStatus" NOT NULL DEFAULT 'PENDING',
    "paymentRef" TEXT,
    "status" "OrderStatus" NOT NULL DEFAULT 'PENDING_PAYMENT',
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Order_pkey" PRIMARY KEY ("id")
);

-- ---- BookingDate (holds/confirms a date range for a Post) ----
CREATE TABLE "BookingDate" (
    "id" TEXT NOT NULL,
    "postId" TEXT NOT NULL,
    "orderId" TEXT,
    "startDate" TIMESTAMP(3) NOT NULL,
    "endDate" TIMESTAMP(3) NOT NULL,
    "status" TEXT NOT NULL DEFAULT 'held',
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "BookingDate_pkey" PRIMARY KEY ("id")
);

-- ---- Foreign keys ----
ALTER TABLE "Order" ADD CONSTRAINT "Order_customerId_fkey" FOREIGN KEY ("customerId") REFERENCES "Customer"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Order" ADD CONSTRAINT "Order_postId_fkey" FOREIGN KEY ("postId") REFERENCES "Post"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "BookingDate" ADD CONSTRAINT "BookingDate_postId_fkey" FOREIGN KEY ("postId") REFERENCES "Post"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "BookingDate" ADD CONSTRAINT "BookingDate_orderId_fkey" FOREIGN KEY ("orderId") REFERENCES "Order"("id") ON DELETE CASCADE ON UPDATE CASCADE;
